# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PomodoroApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PomodoroApp
pod "MBCircularProgressBar"
pod "Eureka"
pod "Charts"
pod 'Instructions', '~> 2.0.1'

end
